[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "anime-analyst"
version = "0.1.0"
dependencies = ["requests>=2.31,<3", "matplotlib>=3.8,<3.10", "numpy>=1.24"]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["anime_analyst"]
